#@TYPE: Machine
#@NAME: uz3eg-iocc
#@DESCRIPTION: Machine support for UltraZed-EG with IOCC customized for LmP

DEFAULTTUNE = "cortexa53"
SOC_VARIANT = "eg"

require conf/machine/include/ultrazed-lmp.inc

# Add system XSA from AvNet 2024.1 release: uz3eg_iocc_base_2024_1/project-spec/hw-description/system.xsa
# To download the BSP:
# Goto: https://avnet.me/ZedSupport
# Click on: 2024.1 -> BSP -> uz3eg_iocc_base_2024_1.bsp
HDF_BASE = "file://"
HDF_PATH = "system.xsa"
HDF_EXT = "xsa"

# Configuration Settings
# From uz3eg_iocc_base_2024_1/project-spec/configs/config

# Yocto device-tree variables
YAML_CONSOLE_DEVICE_CONFIG:pn-device-tree ?= "psu_uart_0"
YAML_MAIN_MEMORY_CONFIG:pn-device-tree ?= "psu_ddr_0"
DT_PADDING_SIZE:pn-device-tree ?= "0x1000"
# Enable DT Overlay
DTC_FLAGS:pn-device-tree ?= " -@"

# Yocto PMUFW variables
extra_settings:pn-pmu-firmware = ""
YAML_COMPILER_FLAGS:append:pn-pmu-firmware = " ${extra_settings}"
YAML_SERIAL_CONSOLE_STDIN:pn-pmu-firmware  = "psu_uart_0"
YAML_SERIAL_CONSOLE_STDOUT:pn-pmu-firmware = "psu_uart_0"

# Serial Console Settings
SERIAL_CONSOLES = "115200;ttyPS0"
YAML_SERIAL_CONSOLE_BAUDRATE = "115200"

# Yocto arm-trusted-firmware(TF-A) variables
ATF_CONSOLE ?= "cadence"
TFA_BL33_LOAD ?= "0x8000000"

## LmP Settings

OSTREE_KERNEL_ARGS ?= "console=ttyPS0,115200 clk_ignore_unused uio_pdrv_genirq.of_id=generic-uio xilinx_tsn_ep.st_pcp=4 ${OSTREE_KERNEL_ARGS_COMMON}"

# bitstream support
MACHINE_FIRMWARE:append = " fpga-manager-script"
MACHINE_EXTRA_RRECOMMENDS += "${MACHINE_FIRMWARE}"
SPL_FPGA_BINARY = "bitstream.bit.bin"
SPL_FPGA_LOAD_ADDR = "0x18000000"
