#@TYPE: Machine
#@NAME: uz3eg-iocc
#@DESCRIPTION: Machine support for UltraZed-EG with IOCC customized for LmP

DEFAULTTUNE = "cortexa53"
SOC_VARIANT = "eg"

require conf/machine/include/ultrazed-lmp.inc

# DSA file taken from UZ3EG_IOCC_2019p1_PetaLinux_SDSoC_Platform.zip ->
#   UZ3EG_IOCC_2019p1_PetaLinux_SDSoC_Platform.tar.gz ->
#     UZ3EG_IOCC/hw/UZ3EG_IOCC.dsa
# https://www.element14.com/community/docs/DOC-93843/l/sdsocplatformv20191pdf?ICID=ultrazedEG-datasheet-widget
HDF_MACHINE ?= "zcu102-zynqmp"
HDF_BASE = "file://"
HDF_PATH = "system.xsa"
HDF_EXT = "xsa"

# Configuration Settings
# From uz3eg_iocc_base_2024_1/project-spec/configs/config

# Yocto device-tree variables
YAML_CONSOLE_DEVICE_CONFIG:pn-device-tree ?= "psu_uart_0"
YAML_MAIN_MEMORY_CONFIG:pn-device-tree ?= "psu_ddr_0"
DT_PADDING_SIZE:pn-device-tree ?= "0x1000"
# Enable DT Overlay
DTC_FLAGS:pn-device-tree ?= " -@"

# Yocto PMUFW variables
extra_settings:pn-pmu-firmware = ""
YAML_COMPILER_FLAGS:append:pn-pmu-firmware = " ${extra_settings}"
YAML_SERIAL_CONSOLE_STDIN:pn-pmu-firmware  = "psu_uart_0"
YAML_SERIAL_CONSOLE_STDOUT:pn-pmu-firmware = "psu_uart_0"

# Serial Console Settings
SERIAL_CONSOLES = "115200;ttyPS0"
YAML_SERIAL_CONSOLE_BAUDRATE = "115200"

# Yocto arm-trusted-firmware(TF-A) variables
ATF_CONSOLE ?= "cadence"
TFA_BL33_LOAD ?= "0x8000000"

# bitstream support
MACHINE_FIRMWARE:append = " fpga-manager-script"
MACHINE_EXTRA_RRECOMMENDS += "${MACHINE_FIRMWARE}"
SPL_FPGA_BINARY = "bitstream.bit.bin"
SPL_FPGA_LOAD_ADDR = "0x18000000"
