# We might have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-partner-amd-xilinx"
BBFILE_PATTERN_meta-partner-amd-xilinx := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-partner-amd-xilinx = "9"

LAYERDEPENDS_meta-partner-amd-xilinx = "meta-lmp-base"
LAYERSERIES_COMPAT_meta-partner-amd-xilinx = "kirkstone"
