# We might have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-partner-nxp-imx"
BBFILE_PATTERN_meta-partner-nxp-imx := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-partner-nxp-imx = "9"

LAYERDEPENDS_meta-partner-nxp-imx = "meta-lmp-base"
LAYERSERIES_COMPAT_meta-partner-nxp-imx = "scarthgap"
