# configuration file for Weston

[core]
#modules=xwayland.so,cms-colord.so
#shell=desktop-shell.so
#gbm-format=xrgb2101010
idle-time=0
require-input=false
require-outputs=none
repaint-window=10
#xwayland=true

[shell]
background-image=/usr/share/weston/backgrounds/background.jpg
background-color=0xff002244
background-type=scale-crop
panel-position=bottom
panel-color=0x90a1a1a1
# optional settings for meta-freescale:weston-init.bbappend
#size=1920x1080

[launcher]
icon=/usr/share/weston/icon/utilities-terminal.png
path=/usr/bin/weston-terminal

#[launcher]
#icon=/usr/share/icons/gnome/24x24/apps/utilities-terminal.png
#path=/usr/bin/gnome-terminal

#[launcher]
#icon=/usr/share/icons/gnome/24x24/apps/utilities-terminal.png
#path=/usr/bin/weston-terminal

#[launcher]
#icon=/usr/share/icons/hicolor/24x24/apps/google-chrome.png
#path=/usr/bin/google-chrome

#[launcher]
#icon=/usr/share/icons/gnome/24x24/apps/arts.png
#path=/build/weston-0lEgCh/weston-1.11.0/weston-flower

#[input-method]
#path=/usr/lib/weston/weston-keyboard

[output]
name=DSI-1
mode=on

[output]
name=DP-1
mode=on

[screen-share]
command=/usr/bin/weston --backend=rdp-backend.so --shell=fullscreen-shell.so --no-clients-resize

#[xwayland]
#path=/usr/bin/Xwayland
