BBMASK:mx8m-nxp-bsp += " \
    /meta-virtualization/recipes-kernel/linux/linux-%.bbappend \
    /meta-virtualization/dynamic-layers/xilinx/recipes-extended/xen/xen_4.14.bbappend \
    /meta-security/meta-integrity/recipes-core/systemd/systemd_%.bbappend \
    /meta-xilinx-tools/recipes-bsp/ai-engine/aiefal_1.0.bb \
    /meta-xilinx-tools/recipes-bsp/u-boot/u-boot-xlnx_%.bbappend \
    /meta-st-stm32mp/recipes-core/busybox/busybox_%.bbappend \
    /meta-st-stm32mp/recipes-graphics/drm/libdrm_2.4.110.bbappend \
    /meta-st-stm32mp/recipes-graphics/drm/libdrm_2.4.113.bbappend \
    /meta-st-stm32mp/recipes-bsp/trusted-firmware-a/tf-a-stm32mp_2.6.bb \
    /meta-ti/meta-ti-bsp/recipes-security/optee/optee-test_%.bbappend \
    /meta-ti/meta-ti-bsp/recipes-security/optee/optee-client_3.16%.bbappend \
    /meta-ti/meta-ti-bsp/recipes-security/optee/optee-os_3.16%.bbappend \
    /meta-ti/meta-ti-bsp/recipes-security/optee/optee-os-tadevkit_%.bbappend \
    /meta-ti/meta-ti-bsp/recipes-security/optee/optee-examples_%.bbappend \
    /meta-phytec/dynamic-layers/stm-st-stm32mp/recipes-bsp/trusted-firmware-a/tf-a-stm32mp_%.bbappend \
    /meta-phytec/recipes-bsp/u-boot/libubootenv_%.bbappend \
"
